import 'package:flutter/material.dart';
import 'package:intl/intl.dart' as intl;
import 'package:provider/provider.dart';
import '../utils/app_styles.dart';
import '../providers/promise_provider.dart';
import '../providers/friends_provider.dart';
import '../providers/auth_provider.dart';
import '../services/database_service.dart';
import '../models/promise_request_model.dart'; // Ensure this model exists or is created
import '../models/user_model.dart';

class NewPromiseScreen extends StatefulWidget {
  const NewPromiseScreen({super.key});

  @override
  State<NewPromiseScreen> createState() => _NewPromiseScreenState();
}

class _NewPromiseScreenState extends State<NewPromiseScreen> {
  static const String fullDateTimeFormat = 'dd/MMM/yy HH:mm';
  static const String dayTimeFormat = 'EEE HH:mm';

  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();

  bool isRecurring = false;
  int difficultyStars = 3;

  // --- CATEGORY STATE ---
  String _selectedCategory = 'Personal';
  final List<String> _categories = ['Work', 'Personal', 'Health', 'Family'];

  // --- SLOTS (User's Duration Structure) ---
  List<Map<String, dynamic>> dynamicSlots = [
    {'start': null, 'duration': {'hours': 1, 'minutes': 0}},
  ];

  // --- FRIEND SHARING (Friend's Feature) ---
  List<String> _selectedFriendUids = [];

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _handleCreatePromise() async {
    if (_nameController.text.trim().isEmpty) {
      _showErrorSnackbar("Please enter a promise name.");
      return;
    }

    bool hasValidSlot = dynamicSlots.any((slot) => slot['start'] != null);
    if (!hasValidSlot) {
      _showErrorSnackbar("Please set a start time for your promise.");
      return;
    }

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      final promiseProvider = Provider.of<PromiseProvider>(context, listen: false);

      // 1. CREATE LOCAL PROMISES
      for (var slot in dynamicSlots) {
        if (slot['start'] != null) {
          final durMap = slot['duration'] as Map<String, int>;
          final totalMinutes = (durMap['hours']! * 60) + durMap['minutes']!;

          await promiseProvider.addPromise(
            title: _nameController.text.trim(),
            description: _descriptionController.text.trim(),
            startTime: slot['start']!,
            durationMinutes: totalMinutes,
            isRecursive: isRecurring,
            category: _selectedCategory,
            priority: difficultyStars,
          );
        }
      }

      // 2. SEND FRIEND REQUESTS (New Feature)
      if (_selectedFriendUids.isNotEmpty) {
        await _sendPromiseRequests();
      }

      if (mounted) {
        Navigator.of(context).pop(); // Close Loader
        Navigator.of(context).pop(); // Close Screen

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Promise(s) saved successfully!'),
            backgroundColor: AppStyles.successGreen,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        Navigator.of(context).pop();
        _showErrorSnackbar("Error saving: $e");
      }
    }
  }

  Future<void> _sendPromiseRequests() async {
    try {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final db = Provider.of<DatabaseService>(context, listen: false);
      final currentUser = authProvider.user;

      if (currentUser != null) {
        for (var friendUid in _selectedFriendUids) {
          for (var slot in dynamicSlots) {
            if (slot['start'] != null) {
              // Calculate EndTime for the request model
              final DateTime start = slot['start'];
              final durMap = slot['duration'] as Map<String, int>;
              final DateTime end = start.add(Duration(hours: durMap['hours']!, minutes: durMap['minutes']!));

              final request = PromiseRequestModel(
                id: '', // Generated by Firestore
                senderUid: currentUser.uid,
                senderName: currentUser.displayName ?? 'Friend',
                title: _nameController.text.trim(),
                description: _descriptionController.text.trim(),
                startTime: start,
                endTime: end, // Pass calculated EndTime
                category: _selectedCategory,
                priority: difficultyStars,
                sentAt: DateTime.now(),
              );
              await db.sendPromiseRequest(friendUid, request);
            }
          }
        }
      }
    } catch (e) {
      debugPrint("Error sending friend requests: $e");
    }
  }

  // --- UI METHODS ---

  void _addSlot() {
    setState(() => dynamicSlots.add({'start': null, 'duration': {'hours': 1, 'minutes': 0}}));
  }

  void _removeSlot(int index) {
    setState(() => dynamicSlots.removeAt(index));
  }

  void _toggleGlobalRecurring(bool? newValue) {
    setState(() {
      isRecurring = newValue ?? isRecurring;
      for (var slot in dynamicSlots) {
        slot['start'] = null;
      }
    });
  }

  Future<void> _pickStartDate(int index) async {
    DateTime now = DateTime.now();
    DateTime? initialDate = dynamicSlots[index]['start'];
    initialDate ??= now;

    final DateTime? pickedDate = await showDatePicker(
      context: context,
      initialDate: initialDate,
      firstDate: DateTime(now.year - 5),
      lastDate: DateTime(now.year + 5),
    );
    if (pickedDate == null) return;

    if (!mounted) return;
    final TimeOfDay? pickedTime = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.fromDateTime(initialDate),
    );
    if (pickedTime == null) return;

    setState(() {
      dynamicSlots[index]['start'] = DateTime(
        pickedDate.year,
        pickedDate.month,
        pickedDate.day,
        pickedTime.hour,
        pickedTime.minute,
      );
    });
  }

  Future<void> _pickDayTime(int index) async {
    final List<String> weekdays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    String? selectedDay = weekdays[0];

    await showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Select Day of Week'),
          content: DropdownButtonFormField<String>(
            initialValue: selectedDay,
            items: weekdays.map((day) => DropdownMenuItem(value: day, child: Text(day))).toList(),
            onChanged: (newValue) => selectedDay = newValue,
          ),
          actions: [
            TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
            TextButton(
              onPressed: () => Navigator.pop(context, selectedDay),
              child: const Text('OK'),
            ),
          ],
        );
      },
    ).then((resultDay) async {
      if (resultDay == null) return;

      final TimeOfDay? pickedTime = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.fromDateTime(DateTime.now()),
      );
      if (pickedTime == null) return;

      DateTime now = DateTime.now();
      int currentWeekday = now.weekday;
      final int dayIndex = weekdays.indexOf(resultDay.toString());
      int targetWeekday = dayIndex + 1;

      DateTime targetDate = now.add(Duration(days: (targetWeekday - currentWeekday + 7) % 7));
      if (targetDate.isBefore(now)) targetDate = targetDate.add(const Duration(days: 7));

      final DateTime finalDateTime = DateTime(
        targetDate.year,
        targetDate.month,
        targetDate.day,
        pickedTime.hour,
        pickedTime.minute,
      );

      setState(() {
        dynamicSlots[index]['start'] = finalDateTime;
      });
    });
  }

  void _pickDuration(int index) async {
    final currentDuration = dynamicSlots[index]['duration'] as Map<String, int>;
    TextEditingController hoursController = TextEditingController(text: currentDuration['hours'].toString());
    TextEditingController minutesController = TextEditingController(text: currentDuration['minutes'].toString());

    await showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Enter Duration'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  SizedBox(
                    width: 70,
                    child: TextField(
                      controller: hoursController,
                      keyboardType: TextInputType.number,
                      textAlign: TextAlign.center,
                      decoration: const InputDecoration(labelText: 'Hrs'),
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.symmetric(horizontal: 8.0),
                    child: Text(':', style: TextStyle(fontSize: 24)),
                  ),
                  SizedBox(
                    width: 70,
                    child: TextField(
                      controller: minutesController,
                      keyboardType: TextInputType.number,
                      textAlign: TextAlign.center,
                      decoration: const InputDecoration(labelText: 'Mins'),
                    ),
                  ),
                ],
              ),
            ],
          ),
          actions: <Widget>[
            TextButton(child: const Text('Cancel'), onPressed: () => Navigator.pop(context)),
            TextButton(
              child: const Text('Set'),
              onPressed: () {
                int hours = int.tryParse(hoursController.text) ?? 0;
                int minutes = int.tryParse(minutesController.text) ?? 0;
                if (hours < 0 || minutes < 0 || (hours == 0 && minutes == 0)) {
                  _showErrorSnackbar("Invalid duration.");
                  return;
                }
                setState(() {
                  dynamicSlots[index]['duration'] = {'hours': hours, 'minutes': minutes};
                });
                Navigator.pop(context);
              },
            ),
          ],
        );
      },
    );
  }

  void _showErrorSnackbar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: AppStyles.errorRed),
    );
  }

  Widget _buildCardSection({required List<Widget> children}) {
    return Container(
      margin: const EdgeInsets.only(top: 20, left: 16, right: 16),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppStyles.white,
        borderRadius: BorderRadius.circular(15.0),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.2),
            spreadRadius: 1,
            blurRadius: 5,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: children),
    );
  }

  Widget _buildTimeSlotChip(String label, bool isSelected, {VoidCallback? onTap}) {
    return InkWell(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
        decoration: BoxDecoration(
          color: isSelected ? AppStyles.primaryPurple : Colors.grey[200],
          borderRadius: BorderRadius.circular(8.0),
          border: isSelected ? Border.all(color: AppStyles.primaryPurple) : null,
        ),
        child: Text(
          label,
          style: TextStyle(color: isSelected ? AppStyles.white : Colors.black87, fontSize: 14),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: AppStyles.primaryPurple,
        title: const Text('New Promise', style: TextStyle(color: AppStyles.white)),
        leading: IconButton(icon: const Icon(Icons.close, color: Colors.white), onPressed: () => Navigator.pop(context)),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.only(bottom: 20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            _buildNameSection(),
            _buildDescriptionSection(),
            _buildCategorySection(),
            _buildSlotsSection(),
            _buildDifficultySection(),
            const SizedBox(height: 20),
            _buildFriendsSection(context), // --- NEW SECTION ---
            const SizedBox(height: 30),
          ],
        ),
      ),
    );
  }

  Widget _buildNameSection() {
    return _buildCardSection(
      children: [
        const Text('Name', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        const SizedBox(height: 8),
        TextField(controller: _nameController, decoration: const InputDecoration(hintText: 'Enter promise name')),
      ],
    );
  }

  Widget _buildDescriptionSection() {
    return _buildCardSection(
      children: [
        const Text('Description', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        const SizedBox(height: 8),
        TextField(controller: _descriptionController, maxLines: 4, decoration: const InputDecoration(hintText: 'Enter promise description')),
      ],
    );
  }

  Widget _buildCategorySection() {
    return _buildCardSection(
      children: [
        const Text('Category', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        const SizedBox(height: 12),
        Wrap(
          spacing: 10,
          runSpacing: 10,
          children: _categories.map((category) {
            final isSelected = _selectedCategory == category;
            return ChoiceChip(
              label: Text(category),
              selected: isSelected,
              onSelected: (selected) {
                if (selected) {
                  setState(() => _selectedCategory = category);
                }
              },
              selectedColor: AppStyles.primaryPurple,
              labelStyle: TextStyle(
                color: isSelected ? Colors.white : Colors.black,
                fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
              ),
            );
          }).toList(),
        ),
      ],
    );
  }

  Widget _buildSlotsSection() {
    final List<Widget> children = [
      Row(children: const [
        Text('Slots', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        SizedBox(width: 8),
        Icon(Icons.access_time, size: 18, color: Colors.grey),
      ]),
      const SizedBox(height: 12),
    ];

    dynamicSlots.asMap().forEach((index, slot) {
      final DateTime? startTime = slot['start'];
      final duration = slot['duration'] as Map<String, int>;

      final dateFormat = isRecurring ? dayTimeFormat : fullDateTimeFormat;
      final startLabel = startTime != null
          ? intl.DateFormat(dateFormat).format(startTime)
          : "Select Start Time";

      final durationLabel = "${duration['hours']}h ${duration['minutes']}m";

      children.add(
        Padding(
          padding: const EdgeInsets.only(bottom: 15.0),
          child: Container(
            padding: const EdgeInsets.all(12.0),
            decoration: BoxDecoration(
              color: AppStyles.white,
              borderRadius: BorderRadius.circular(10.0),
              border: Border.all(color: Colors.grey.shade300),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text("Slot ${index+1}", style: const TextStyle(fontWeight: FontWeight.w600)),
                    if (dynamicSlots.length > 1)
                      InkWell(
                        onTap: () => _removeSlot(index),
                        child: const Icon(Icons.delete_outline, color: Colors.red, size: 20),
                      )
                  ],
                ),
                const SizedBox(height: 10),
                Row(
                  children: [
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text("Start", style: TextStyle(fontSize: 12, color: Colors.grey)),
                          const SizedBox(height: 4),
                          _buildTimeSlotChip(
                            startLabel,
                            startTime != null,
                            onTap: () => isRecurring ? _pickDayTime(index) : _pickStartDate(index),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text("Duration", style: TextStyle(fontSize: 12, color: Colors.grey)),
                          const SizedBox(height: 4),
                          _buildTimeSlotChip(
                            durationLabel,
                            true,
                            onTap: () => _pickDuration(index),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      );
    });

    children.addAll([
      GestureDetector(
        onTap: _addSlot,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [
            Icon(Icons.add_circle_outline, color: AppStyles.primaryPurple),
            SizedBox(width: 5),
            Text('Add another slot', style: TextStyle(color: AppStyles.primaryPurple, fontWeight: FontWeight.bold)),
          ],
        ),
      ),
      const SizedBox(height: 15),
      Row(
        children: [
          const Text('Recurring Task (Weekly)', style: TextStyle(fontSize: 14)),
          Checkbox(value: isRecurring, onChanged: _toggleGlobalRecurring, activeColor: AppStyles.primaryPurple),
        ],
      ),
    ]);

    return _buildCardSection(children: children);
  }

  Widget _buildDifficultySection() {
    return _buildCardSection(
      children: [
        const Text('Priority', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        const SizedBox(height: 8),
        Row(
          children: List.generate(5, (index) {
            return IconButton(
              onPressed: () => setState(() => difficultyStars = index + 1),
              icon: Icon(
                index < difficultyStars ? Icons.star : Icons.star_border,
                color: Colors.yellow[700],
              ),
            );
          }),
        ),
        const SizedBox(height: 20),
        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            onPressed: _handleCreatePromise,
            style: ElevatedButton.styleFrom(
              backgroundColor: AppStyles.primaryPurple,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
            ),
            child: const Text('Create Promise', style: TextStyle(color: Colors.white)),
          ),
        ),
      ],
    );
  }

  // --- NEW: FRIENDS SECTION WIDGET ---
  Widget _buildFriendsSection(BuildContext context) {
    return _buildCardSection(
      children: [
        Row(
          children: const [
            Text(
              'Share with Friends',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
            ),
            SizedBox(width: 8),
            Icon(Icons.people_outline, size: 18, color: Colors.grey),
          ],
        ),
        const SizedBox(height: 8),
        StreamBuilder<List<UserModel>>(
          stream: Provider.of<FriendsProvider>(context, listen: false).friendsStream,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            }

            final friends = snapshot.data ?? [];

            if (friends.isEmpty) {
              return const Padding(
                padding: EdgeInsets.symmetric(vertical: 8.0),
                child: Text(
                  "You haven't added any friends yet.",
                  style: TextStyle(color: Colors.grey),
                ),
              );
            }

            return Column(
              children: [
                ...friends.map((friend) {
                  final isSelected = _selectedFriendUids.contains(friend.uid);
                  return CheckboxListTile(
                    title: Text(friend.displayName),
                    subtitle: Text(friend.email),
                    value: isSelected,
                    activeColor: AppStyles.primaryPurple,
                    onChanged: (bool? value) {
                      setState(() {
                        if (value == true) {
                          _selectedFriendUids.add(friend.uid);
                        } else {
                          _selectedFriendUids.remove(friend.uid);
                        }
                      });
                    },
                  );
                }),
              ],
            );
          },
        ),
      ],
    );
  }
}